language: csharp
dotnet: 3.1.301
solution: Cake.ApiReference.Uploader.sln

install:
  - curl -L -o nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - dotnet --list-sdks
  - mono nuget.exe restore Cake.ApiReference.Uploader.sln
##- mono nuget.exe install NUnit.Runners -Version 3.6.1 -OutputDirectory testrunner

script:
  - xbuild /p:Configuration=Release Cake.ApiReference.Uploader.sln
##  - mono ./testrunner/NUnit.ConsoleRunner.3.6.1/tools/nunit3-console.exe ./<Project Name>Test/bin/Release/<Project Name>Test.dll
  - mono nuget.exe pack Cake.ApiReference.Uploader.nuspec -Version $MAJOR_VERSION_NUMBER.$MINOR_VERSION_NUMBER.$TRAVIS_BUILD_NUMBER
  - mono nuget.exe setApiKey $NUGET_API_KEY -Source https://www.nuget.org -Verbosity quiet
  - mono nuget.exe push Cake.ApiReference.Uploader.$MAJOR_VERSION_NUMBER.$MINOR_VERSION_NUMBER.$TRAVIS_BUILD_NUMBER.nupkg -Source https://www.nuget.org/api/v2/package  